name: Go

on: [pull_request]

jobs:

  unit-test:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Test
      run: |
        go test -v ./...

  schema-validation:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Test schema validation
      run: go test -v ./...
      working-directory: internal/jsonschema

    - name: Check schemas are up to date
      run: |
        make -C internal/jsonschema json yaml
        git diff --exit-code schemas/

  govulncheck:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run govulncheck
      run: govulncheck ./...

